# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('nom_proprietaire', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'compte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                 serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_ope', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True
                    )),
                ('debit', models.CharField(blank=True, max_length=5, null=True)
                    ),
                ('description', models.CharField(blank=True, max_length=150,
                 null=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_operations.Compte')),
                ('type_0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_operations.Types')),
            ],
            options={
                'db_table': 'operation',
                'managed': True,
            },
        ),
    ]
