# Generated by Django 2.0.2 on 2018-03-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_operations', '0006_auto_20170808_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': False},
        ),
    ]
