# Generated by Django 2.0.2 on 2018-03-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_operations', '0007_auto_20180311_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'managed': True},
        ),
    ]
