# Generated by Django 2.0.2 on 2018-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_operations', '0008_auto_20180311_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='types',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='types',
            name='nom',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
