# Generated by Django 2.0.2 on 2018-03-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_operations', '0009_auto_20180311_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': False},
        ),
    ]
