# Generated by Django 2.0.2 on 2018-03-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_operations', '0010_auto_20180311_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'managed': False},
        ),
    ]
