# Generated by Django 3.2.10 on 2022-01-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_operations', '0011_auto_20180311_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': True},
        ),
    ]
