# Generated by Django 3.2.10 on 2022-01-02 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_operations', '0012_auto_20220101_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'managed': False},
        ),
    ]
